resources:
- ../../../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: demo-nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
