apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-other
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      project.cpaas.io/name: product-demo
      service.cpaas.io/name: deployment-demo-nginx-other
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: admin@alauda.io
      creationTimestamp: null
      labels:
        project.cpaas.io/name: product-demo
        service.cpaas.io/name: deployment-demo-nginx-other
    spec:
      affinity: {}
      containers:
        - image: registry.alauda.cn:60080/automation/qaimages:helloworld
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-other
spec:
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: tcp
      name: tcp-80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    service.cpaas.io/name: deployment-demo-nginx-other
  sessionAffinity: None
  type: ClusterIP
