resources:
- ../../xf-demo

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: application-qaimages
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
