resources:
- ../../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: demo-res-app-qaimages
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
